import a_search
import matplotlib.pyplot as plt

# Open file
lst = []
for i in range(1,17):
	total_num_states = 0
	for n_test in range(1,11):
		file = open(str(i) + "/instance_" + str(n_test) + ".txt", 'r')
		print(str(i) + "/instance_" + str(n_test) + ".txt")
		unvisited_nodes = a_search.create_nodes(file)
		edge_costs = a_search.calculate_cost(unvisited_nodes)
		num_states = a_search.a_search(unvisited_nodes, edge_costs)
		print(num_states)
		total_num_states += num_states
	lst.append(total_num_states/10)


x = [ i for i in range(1,18)]
plt.yscale('log')
plt.scatter(x, lst)
plt.title('Number of States generated by A*')
plt.xlabel('Number of Cities')
plt.ylabel('Number of States')
plt.show()
