import a_search
import matplotlib.pyplot as plt

"""
Script to test 'a_search.py'
Test cases can be found in "../Examples" and are divided into folders by
the number of cities in each example. i.e. "/Examples/10" only contain test cases
of 10 cities.

The script also plots the average number of states generated by the A* Search algorithm
for each number of nodes/cities.
"""
lst = []
for i in range(1,17):
	total_num_states = 0
	for n_test in range(1,11):
		file = open("examples/" + str(i) + "/instance_" + str(n_test) + ".txt", 'r')
		print(str(i) + "/instance_" + str(n_test) + ".txt")
		unvisited_nodes = a_search.create_nodes(file)
		edge_costs = a_search.calculate_cost(unvisited_nodes)
		results = a_search.a_search(unvisited_nodes, edge_costs)
		if not results:
			print("Error at test case" + str(i) + "/instance_" + str(n_test) + ".txt")
		else:
			total_num_states += results["num_states"]
	lst.append(total_num_states/10)


x = [ i for i in range(1,17)]
plt.yscale('log')
plt.scatter(x, lst)
plt.title('Number of States generated by A*')
plt.xlabel('Number of Cities')
plt.ylabel('Number of States')
plt.show()
